<?php
namespace App\Auth\View;

class Users extends \Spoon\View
{
    public function __construct()
    {
        parent::__construct();
        $this->_rules=array(
            'workid'=>array(
                'type'=>'regex',
                'pattern'=>'/^\d{5,7}$/'
            ),
            'password'=>array(
                'type'=>'text',
                'length-max'=>16,
                'length-min'=>6
            ),
            'username'=>array(
                'type'=>'text',
                'length-max'=>20
            ),
            'depart'=>array(
                'type'=>'list',
                'list'=>array('Logistics','CS')
            ),
            'email'=>array(
                'type'=>'regex',
                'pattern'=>'/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/'
            ),
            'phone'=>array(
                'type'=>'text',
                'max-length'=>20
            ),
            'infofields'=>array(
                'type'=>'list',
                'list'=>array('username','depart','email','phone')
            ),
            'info'=>array(
                'type'=>'array',
                'require'=>array(),
                'optional'=>array('username','depart','email','phone')
            ),
            'groupname'=>array(
                'type'=>'text'
            ),
            'rolename'=>array(
                'type'=>'text'
            )
        );
    }
}
